import requests
import json
import os
import sys

BASE_URL = "http://127.0.0.1:8000"

def run_verify():
    print("==================================================")
    print("RUNNING KNOWLEDGE BASE ENDPOINT VERIFICATION")
    print("==================================================")
    
    # 1. Test GET /rag/documents
    print("\n[TEST 1] List active policy documents...")
    try:
        r = requests.get(f"{BASE_URL}/rag/documents", timeout=5)
        if r.status_code == 200:
            data = r.json()
            print(f"SUCCESS: Found {data.get('total', 0)} documents.")
            if data.get("documents"):
                first_doc = data["documents"][0]
                print(f"Sample: {first_doc.get('filename')} | Category: {first_doc.get('category')} | Version: {first_doc.get('version')}")
        else:
            print(f"FAILED with status {r.status_code}: {r.text}")
            sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    # 2. Test POST /rag/documents (Create new text policy)
    print("\n[TEST 2] Create new temporary policy...")
    test_filename = "temp_verification_policy.txt"
    payload = {
        "filename": test_filename,
        "category": "Security",
        "content": "AMAZON INDIA VERIFICATION SECURITY RULES\n\nCustomers must provide their registered email address and last four digits of their card to verify identity before agents share order status details.",
        "comment": "Adding temporary verification policy for automated test suite"
    }
    try:
        r = requests.post(f"{BASE_URL}/rag/documents", json=payload, timeout=10)
        if r.status_code == 200:
            print(f"SUCCESS: {r.json().get('message')}")
        else:
            print(f"FAILED with status {r.status_code}: {r.text}")
            sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    # 3. Verify it was indexed and query it
    print("\n[TEST 3] Querying the newly indexed policy...")
    query_payload = {"question": "What details are required to verify customer identity?"}
    try:
        r = requests.post(f"{BASE_URL}/agent/respond", json={
            "caller_phone": "+919876543210",
            "message": "What details do you need to verify my identity?"
        }, timeout=10)
        if r.status_code == 200:
            res_data = r.json()
            print(f"SUCCESS: Response generated by agent.")
            print(f"Intent detected: {res_data.get('intent')}")
            try:
                print(f"Grounded Response: {res_data.get('answer')}")
            except UnicodeEncodeError:
                print(f"Grounded Response: {res_data.get('answer').encode('ascii', 'replace').decode('ascii')}")
        else:
            print(f"FAILED with status {r.status_code}: {r.text}")
            sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    # 4. Test PUT /rag/documents/{filename} (Edit content)
    print("\n[TEST 4] Updating policy content to bump version...")
    form_data = {
        "content": "AMAZON INDIA VERIFICATION SECURITY RULES\n\nCustomers must provide their registered email address, phone number, and last four digits of their card to verify identity. Post-verification, L2 support agents can check details.",
        "comment": "Bumped security requirements to include phone number"
    }
    try:
        r = requests.put(f"{BASE_URL}/rag/documents/{test_filename}", data=form_data, timeout=10)
        if r.status_code == 200:
            print(f"SUCCESS: {r.json().get('message')}")
        else:
            print(f"FAILED with status {r.status_code}: {r.text}")
            sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    # 5. Test GET /rag/documents/{filename}/history
    print("\n[TEST 5] Fetch version change history...")
    try:
        r = requests.get(f"{BASE_URL}/rag/documents/{test_filename}/history", timeout=5)
        if r.status_code == 200:
            data = r.json()
            print(f"SUCCESS: Found {len(data.get('history', []))} versions.")
            for ver in data.get("history", []):
                print(f" - Version {ver.get('version')}: '{ver.get('comment')}' at {ver.get('timestamp')}")
        else:
            print(f"FAILED with status {r.status_code}: {r.text}")
            sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    # 6. Test GET /rag/retrieval/logs and analytics
    print("\n[TEST 6] Fetch retrieval analytics and logs...")
    try:
        r_logs = requests.get(f"{BASE_URL}/rag/retrieval/logs", timeout=5)
        r_an = requests.get(f"{BASE_URL}/rag/retrieval/analytics", timeout=5)
        if r_logs.status_code == 200 and r_an.status_code == 200:
            print(f"SUCCESS: Retrieval logs size: {len(r_logs.json().get('logs', []))} entries.")
            print(f"Analytics summary: Total Queries: {r_an.json().get('total_queries')} | Avg Latency: {r_an.json().get('avg_latency_ms')}ms")
        else:
            print(f"FAILED to fetch search telemetry")
            sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    # 7. Test DELETE /rag/documents/{filename} (Clean up)
    print("\n[TEST 7] Cleaning up temporary policy...")
    try:
        r = requests.delete(f"{BASE_URL}/rag/documents/{test_filename}", timeout=10)
        if r.status_code == 200:
            print(f"SUCCESS: {r.json().get('message')}")
        else:
            print(f"FAILED with status {r.status_code}: {r.text}")
            sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}")
        sys.exit(1)

    print("\n==================================================")
    print("KNOWLEDGE BASE ENDPOINTS VERIFIED SUCCESSFULLY.")
    print("==================================================")

if __name__ == "__main__":
    run_verify()
