import React, { useState, useEffect } from 'react';
import { getTickets, updateTicketStatus } from '../api/client';
import { demoTickets } from '../data/demoData';
import { Ticket, AlertTriangle, Clock, RotateCw, Filter, User, CheckCircle2, RefreshCcw, Save } from 'lucide-react';

const Tickets = () => {
  const [tickets, setTickets] = useState(demoTickets);
  const [isLive, setIsLive] = useState(false);
  const [refreshing, setRefreshing] = useState(false);

  // Filter States
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [priorityFilter, setPriorityFilter] = useState('ALL');

  // Expanded editor for resolution notes
  const [editingId, setEditingId] = useState(null);
  const [notesDraft, setNotesDraft] = useState('');
  const [statusDraft, setStatusDraft] = useState('');

  const fetchTickets = async (silent = false) => {
    if (!silent) setRefreshing(true);
    try {
      const data = await getTickets();
      if (data && data.length > 0) {
        setTickets(data);
        setIsLive(true);
      } else {
        setIsLive(true);
      }
    } catch (e) {
      console.warn('[SupportGenie] Using fallback demo tickets:', e.message);
      setIsLive(false);
    } finally {
      setRefreshing(false);
    }
  };

  useEffect(() => {
    fetchTickets();
    const interval = setInterval(() => {
      fetchTickets(true);
    }, 5000);
    return () => clearInterval(interval);
  }, []);

  const handleUpdateStatus = async (ticketId, status, notes = null) => {
    try {
      await updateTicketStatus(ticketId, status, notes);
      // Immediately refresh list
      fetchTickets(true);
      setEditingId(null);
      setNotesDraft('');
    } catch (e) {
      console.error('[SupportGenie] Failed to update ticket status:', e);
      // Fallback update in state for demo purposes if backend fails
      setTickets(prev => prev.map(t => {
        if (t.ticket_id === ticketId) {
          return {
            ...t,
            status,
            resolution_notes: notes || t.resolution_notes,
            updated_at: new Date().toISOString()
          };
        }
        return t;
      }));
    }
  };

  // Filter logic
  const filteredTickets = tickets.filter(t => {
    const matchStatus = statusFilter === 'ALL' || t.status.toUpperCase() === statusFilter;
    const matchPriority = priorityFilter === 'ALL' || t.priority.toUpperCase() === priorityFilter;
    return matchStatus && matchPriority;
  });

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-50">Escalation Tickets</h1>
          <p className="text-slate-400 text-sm mt-1">High-priority support requests generated by AI Agent and routed to human managers</p>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2">
            <span className={`h-2.5 w-2.5 rounded-full ${isLive ? 'bg-emerald-500 animate-pulse' : 'bg-amber-500'}`} />
            <span className="text-xs text-slate-400 font-medium">
              {isLive ? 'Live Database feed' : 'Demo Offline Sandbox'}
            </span>
          </div>
          <button
            onClick={() => fetchTickets(false)}
            className="p-2 rounded-lg bg-slate-800/80 border border-slate-700 hover:bg-slate-700 text-slate-300 hover:text-slate-50 transition-colors flex items-center gap-1.5 text-xs"
            disabled={refreshing}
          >
            <RotateCw className={`w-3.5 h-3.5 ${refreshing ? 'animate-spin' : ''}`} />
            Refresh
          </button>
        </div>
      </div>

      {/* Filter toolbar */}
      <div className="bg-slate-900/40 border border-slate-800 rounded-xl p-4 flex flex-wrap gap-4 items-center justify-between">
        <div className="flex items-center gap-2 text-slate-400 text-xs font-semibold uppercase tracking-wider">
          <Filter className="w-4 h-4 text-rose-400" />
          Filter Tickets
        </div>
        
        <div className="flex gap-4">
          <div className="flex flex-col gap-1">
            <label className="text-[10px] text-slate-500 font-medium uppercase">Status</label>
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="bg-slate-950 border border-slate-800 rounded-lg px-2.5 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-orange-500 transition-colors"
            >
              <option value="ALL">All Statuses</option>
              <option value="OPEN">Open</option>
              <option value="IN_PROGRESS">In Progress</option>
              <option value="RESOLVED">Resolved</option>
            </select>
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-[10px] text-slate-500 font-medium uppercase">Priority</label>
            <select
              value={priorityFilter}
              onChange={(e) => setPriorityFilter(e.target.value)}
              className="bg-slate-950 border border-slate-800 rounded-lg px-2.5 py-1.5 text-xs text-slate-300 focus:outline-none focus:border-orange-500 transition-colors"
            >
              <option value="ALL">All Priorities</option>
              <option value="HIGH">High</option>
              <option value="MEDIUM">Medium</option>
              <option value="LOW">Low</option>
            </select>
          </div>
        </div>
      </div>

      {/* Grid of tickets */}
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
        {filteredTickets.map((ticket, i) => {
          const isEditing = editingId === ticket.ticket_id;
          const isResolved = ticket.status.toLowerCase() === 'resolved';
          const isInProgress = ticket.status.toLowerCase() === 'in progress' || ticket.status.toLowerCase() === 'in_progress';
          const isOpen = ticket.status.toLowerCase() === 'open';

          let statusBadgeColor = 'bg-rose-500/10 text-rose-400 border-rose-500/20';
          if (isResolved) statusBadgeColor = 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20';
          if (isInProgress) statusBadgeColor = 'bg-amber-500/10 text-amber-400 border-amber-500/20';

          return (
            <div key={i} className={`bg-slate-900/50 border rounded-2xl p-6 relative overflow-hidden group transition-all duration-300 ${
              isResolved ? 'border-emerald-500/20 hover:border-emerald-500/40' : 'border-rose-500/20 hover:border-rose-500/40'
            }`}>
              <div className={`absolute top-0 left-0 w-1.5 h-full ${
                isResolved ? 'bg-emerald-500' : isInProgress ? 'bg-amber-500' : 'bg-rose-500'
              }`} />
              
              <div className="flex justify-between items-start mb-4">
                <div className="flex items-center">
                  <Ticket className="w-5 h-5 text-orange-400 mr-2" />
                  <span className="font-mono text-sm text-slate-300 font-semibold">{ticket.ticket_id}</span>
                </div>
                <span className={`px-2.5 py-1 rounded text-xs font-semibold uppercase tracking-wider border ${statusBadgeColor}`}>
                  {ticket.status}
                </span>
              </div>
              
              <div className="grid grid-cols-2 gap-4 mb-4">
                <div>
                  <p className="text-[10px] text-slate-500 uppercase font-medium">Customer Phone</p>
                  <p className="text-sm font-medium text-slate-200">{ticket.caller_phone}</p>
                </div>
                <div>
                  <p className="text-[10px] text-slate-500 uppercase font-medium">Priority</p>
                  <p className="text-sm font-medium text-rose-400">{ticket.priority}</p>
                </div>
              </div>

              <div className="mb-4">
                <p className="text-[10px] text-slate-500 uppercase font-medium mb-1">Escalation Reason</p>
                <p className="text-sm text-slate-300 leading-relaxed bg-slate-950/40 px-3 py-2 rounded-lg border border-slate-800/80">{ticket.reason}</p>
              </div>

              <div className="bg-slate-950/90 rounded-lg p-3.5 border border-slate-800/60 mb-4">
                <p className="text-[10px] text-slate-500 uppercase font-medium mb-1">Call Transcript Context</p>
                <p className="text-xs text-slate-400 italic leading-relaxed">"{ticket.transcript}"</p>
              </div>

              {ticket.resolution_notes && (
                <div className="bg-emerald-500/5 rounded-lg p-3 border border-emerald-500/10 mb-4">
                  <p className="text-[10px] text-emerald-400 uppercase font-semibold mb-1">Resolution Notes</p>
                  <p className="text-xs text-emerald-100">{ticket.resolution_notes}</p>
                </div>
              )}

              {/* Status Update Form / Actions */}
              <div className="border-t border-slate-800/80 pt-4 mt-4">
                {isEditing ? (
                  <div className="space-y-3">
                    <div>
                      <label className="text-[10px] text-slate-400 uppercase font-medium block mb-1">Change Status To</label>
                      <select
                        value={statusDraft}
                        onChange={(e) => setStatusDraft(e.target.value)}
                        className="w-full bg-slate-950 border border-slate-800 rounded-lg px-2 py-1.5 text-xs text-slate-300 focus:outline-none"
                      >
                        <option value="Open">Open</option>
                        <option value="In Progress">In Progress</option>
                        <option value="Resolved">Resolved</option>
                      </select>
                    </div>

                    {statusDraft === 'Resolved' && (
                      <div>
                        <label className="text-[10px] text-slate-400 uppercase font-medium block mb-1">Resolution Summary</label>
                        <textarea
                          placeholder="Provide summary of final customer resolution..."
                          value={notesDraft}
                          onChange={(e) => setNotesDraft(e.target.value)}
                          className="w-full h-16 bg-slate-950 border border-slate-800 rounded-lg p-2 text-xs text-slate-300 focus:outline-none resize-none"
                        />
                      </div>
                    )}

                    <div className="flex gap-2 justify-end text-xs">
                      <button
                        onClick={() => setEditingId(null)}
                        className="px-3 py-1.5 rounded-lg border border-slate-700 hover:bg-slate-800 text-slate-400"
                      >
                        Cancel
                      </button>
                      <button
                        onClick={() => handleUpdateStatus(ticket.ticket_id, statusDraft, statusDraft === 'Resolved' ? notesDraft : null)}
                        className="px-3 py-1.5 rounded-lg bg-orange-600 hover:bg-orange-500 text-slate-50 flex items-center gap-1 font-semibold cursor-pointer"
                      >
                        <Save className="w-3.5 h-3.5" />
                        Apply
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="flex justify-between items-center gap-2">
                    <span className="flex items-center text-[10px] text-slate-500">
                      <Clock className="w-3 h-3 mr-1" />
                      {new Date(ticket.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                    {!isResolved && (
                      <button
                        onClick={() => {
                          setEditingId(ticket.ticket_id);
                          setStatusDraft(ticket.status === 'Open' ? 'In Progress' : ticket.status);
                          setNotesDraft(ticket.resolution_notes || '');
                        }}
                        className="px-3 py-1.5 rounded-lg bg-slate-800 border border-slate-700 hover:bg-slate-700 text-orange-400 hover:text-orange-300 text-xs font-semibold transition-colors flex items-center gap-1 cursor-pointer"
                      >
                        <RefreshCcw className="w-3 h-3" />
                        Manage Status
                      </button>
                    )}
                  </div>
                )}
              </div>
            </div>
          );
        })}
        
        {filteredTickets.length === 0 && (
          <div className="col-span-full text-center text-slate-500 py-16 bg-slate-900/10 border border-dashed border-slate-800 rounded-2xl">
            No support tickets match the selected filters.
          </div>
        )}
      </div>
    </div>
  );
};

export default Tickets;
